### ISSUE TITLE
[QUESTION] Are there any Visitor or Iterator (e.g. node.iter_imports()) for function call?

### ISSUE THREAD

**Issue by ChangeType** [davidhalter/parso#105]
First of all, thank you so much for the amazing tool.
I am asking this question after searching for the answer a couple of hours. 

My requirement 
Example:
```
def _bn_relu_conv(nb_filter, nb_row, nb_col, subsample=(1, 1)):
       .
       .
       .
        norm = BatchNormalization(mode=0, axis=1)(input)
        activation = Activation.ready("relu")(norm)
        return Convolution2D(nb_filter=nb_filter, nb_row=nb_row, nb_col=nb_col)
 

```

I want to extract all the function calls inside the above code.
i.e.
```
BatchNormalization
Activation.ready
Convolution2D
```

I was using the ast module from Python and then I heard about this tool (parso)  from one of my friends. I was so amaized after doing a couple of experiments. 
To extract function calls, what I do with ast module in Python is:
- extend the class [ast.NodeVisitor](https://docs.python.org/3/library/ast.html#ast.NodeVisitor) 
- use [visit_Call](https://greentreesnakes.readthedocs.io/en/latest/nodes.html#Call) method to extract method calls. 

I am not sure about the proper way of doing this with parso. If someone can help me with this, it would be a great help for me. 

Thanks in advance.

**Comment by davidhalter** [comment]
I usually write this stuff myself recursively :) I don't think there's really a need for such a pattern at the moment, since it's just pure syntax nodes (and not an AST that feels more useful :)).

I just do something like this:

```
def get_function_calls(nodes):
    for node in nodes:                                               
        try:                                                         
            children = node.children                                 
        except AttributeError:                                       
            # Is a leaf, you don't care about that.
            pass                               
        else:                                                        
            # We only want to check foo in foo.bar                   
            if node.type == 'trailer' and node.children[0] == '(':   
                yield node
            yield from get_function_calls(nodes)
```

I'm closing, because this is not really an issue but a question. Feel free to ask further questions here though.

As another potential solution there's https://github.com/Instagram/LibCST which depends on parso, so maybe that's a better fit?! That library is trying to wrap parso in a kind of round-trippable AST.

**Comment by ChangeType** [comment]
Thanks! this is really helpful.
