### ISSUE TITLE
Confusing returned value for get_leaf_for_position

### ISSUE THREAD

**Issue by marcglobality** [davidhalter/parso#147]
```
file_contents = """
def foo(x):
    pass

"""
module = parso.parse(file_contents)
foo = module.children[0]
print(foo.get_params())
# [<Param: <Name: x@2,8>>]
module.get_leaf_for_position((2, 8)), module.get_leaf_for_position((2, 9))
# (<Operator: (>, <Name: x@2,8>)
```

Is this a bug? I would expect calling `get_leaf_for_position(pos)` returning `x`

**Comment by davidhalter** [comment]
It's not a bug, it has always been this way intentionally. Since Parso thinks of positions as "between" characters, it's not 100% clear how we can match. Parso matches the bracket first (as it does with all other leaves that are just before the position).

However I kind of agree that this is confusing. I will think a little bit about this and if nothing changes I will at least update the docstring.

In your case you could probably just use `module.get_leaf_for_position((2, x + 1)` and you would be fine, because a leaf has always the width of one (except of course for newlines, where the width is basically one line).

**Comment by marcglobality** [comment]
I solved it by doing this
```
pos = params[0].end_pos
pos = (pos[0], pos[1] - len(params[0].name.value))
```
but thanks for the answer

**Comment by davidhalter** [comment]
What are you trying to accomplish with this?

**Comment by marcglobality** [comment]
Working on a postprocessor on top of black to explode function definitions, e.g:
```
def func(
   p1, p2,
) 
```
to
```
def func(
   p1, 
   p2,
)
```
got it working, so no worries. Next step is to explode function calls and comprehensions :) WIP
