### ISSUE TITLE
Travis -> Github Actions

### ISSUE THREAD

**Issue by isidentical** [davidhalter/parso#155]
It would be nicer for us to move from travis to github actions, since the GA ecosystem is much bigger now (which we can automate a few tasks, like publishing to PyPI) and travis's new open-source pricing model (not sure whether if effects us or not though).

**Comment by davidhalter** [comment]
I think the Travis pricing model change does not affect us, but I'm not 100% sure. If you want to change to GitHub Actions, I'm totally fine with that.

About publishing to PyPI, I'm not sure I want that. I actually like that a cloud service cannot do that by accident (or because of a security issue in GitHub Actions). If you want the necessary rights to do releases, I'm happy to give you access to publish on PyPI. It's just that I have my concerns about the security/safety aspect.

The releases are so rare that I doubt that we need to change something there. However as a CI I have no problem at all with this.

**Comment by isidentical** [comment]
> About publishing to PyPI, I'm not sure I want that. I actually like that a cloud service cannot do that by accident (or because of a security issue in GitHub Actions). If you want the necessary rights to do releases, I'm happy to give you access to publish on PyPI. It's just that I have my concerns about the security/safety aspect.

Oh, okay. Was just giving an example of automations.

**Comment by blueyed** [comment]
FWIW deploying to PyPI is also possible from Travis CI.

**Comment by gousaiyang** [comment]
I've created #185 for this. Travis CI (`travis-ci.com`) stopped running on my projects several months ago. When you have used up the "initial credits", you either have to become a paid customer, or email them to apply for credits for open source projects. Today when I see the [parso Travis CI page](https://travis-ci.org/github/davidhalter/parso) (which is on `travis-ci.org`), it says `Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.`. Probably this is the time to move to GitHub Actions.

My current PR tries to preserve the original build jobs. Whether to use CI for automated publishing is our freedom of choice and is a separate thing to consider in the future if we want to do that.
