### ISSUE TITLE
parso vs. built in ast lib

### ISSUE THREAD

**Issue by yifanwu** [davidhalter/parso#164]
Hi there!

Thanks for maintaining the library. I came here through the `jedi` library.

I'm looking to do some AST manipulation also and was wondering how `parso` differs from `ast`.  From my cursory inspection, the two are similar---what motivated you to create `parso`, or rather, when should one use `parso` over `ast`?

Thanks so much!

**Comment by isidentical** [comment]
I'm not the original author, but can answer for this question

> I'm looking to do some AST manipulation also and was wondering how parso differs from ast.

Well, the output of `parso.parse` is kind-of similar to the output of `ast.parse`, they both produce syntax trees. But one produces a CST (Concrete Syntax Tree) and the other one produces an AST (Abstract Syntax Tree). I'm pretty sure that you can find a lot of wiki pages about what are these exactly, but basically, one represents the source with all details (fully roundtripable) and the other one is an abstracted way of the CST which is easier and convenient to build static analyzers but loosy in some way (doesn't preserve whitespace, unnecesary parentheses, comments etc.).

It depends on your project to use which one, like if you are building a code formatter (such as black, unimport) or something that edits and refactors the user code (like FixIt), you should use CSTs (there are also other ways, like `token-level-manipulation backed by AST` etc. but this is the most convenient one). If you are building a static analyzer (like mypy, or flake8) you could use both but the most convenient one is the AST. Since working and analyzing CSTs (depending on how they structured) IMHO is waaay messy. 

I'd also like to say, being able to give a CST is not the sole difference (though this makes `parso` similiar to the `lib2to3`'s CST implementation, not `ast` module). `parso` can also do error-recovery (parse code that is actually complete), caching tree fragments, and I think most importantly parse different python versions on any support version (like `ast` module can only parse python version that it's in, not the upper ones, but on the other hand parso can parse everything between 3.6-3.10).

**Comment by davidhalter** [comment]
Thanks for explaining @isidentical. I'm closing, but feel free to ask further questions.
