### ISSUE TITLE
Make the TokenInfo objects more compatible with the standard library tokenize

### ISSUE THREAD

**Issue by asmeurer** [davidhalter/parso#181]
It would be helpful if the tokenize token objects were more compatible with the standard library tokenize. Right now I have to write some shim code to swap them out. Specifically, the `exact_type` and `end` attributes are not present in the parso TokenInfo object. `exact_type` isn't a huge deal. I can just compare strings if the type is `OP`. `end` is more annoying, especially since multiline string tokens can span multiple lines. Is there a reason it can't be included in the parso model?

As a separate aside, why is version_info a required argument of `tokenize`? Can we make it a keyword argument that defaults to `parse_version_string()`?

**Comment by davidhalter** [comment]
I don't like the `tokenize` module at all, that's why I decided to make my own. The two modules have diverged so far, that you couldn't say they have much in common anymore. 

Note that the parso tokenizer is not documented and as such not really public. I at least don't consider it to be. I probably just mentioned it to you because you seem to be running into stdlib tokenizer issues again and again :). Why is it an issue for you to call `end_pos` instead of `end`?

> As a separate aside, why is version_info a required argument of tokenize? Can we make it a keyword argument that defaults to parse_version_string()?

That would of course be a fine patch.

**Comment by asmeurer** [comment]
Oh I didn't notice that it was called end_pos instead of end (and it isn't listed in the repr).

> Note that the parso tokenizer is not documented and as such not really public. I at least don't consider it to be. I probably just mentioned it to you because you seem to be running into stdlib tokenizer issues again and again :). Why is it an issue for you to call end_pos instead of end?

Should I be concerned about using it then? I don't want to use it if it will go away of have a huge API break in the future. Maybe I should see if I can do the same sorts of things I am doing with `tokenize` with the top-level parso parser?

**Comment by davidhalter** [comment]
> Should I be concerned about using it then? 

Yes and No. 

Yes, because it's not public, but then again parso in general is not 1.0 and could break... I mean look at how the latest 3.10 grammar is changing... We somehow need to integrate that.

No, because the tokenizer hasn't really changed significantly in years. F-Strings have been added and some other minor features, but it has stayed pretty consistent (apart from minor API changes like `end` -> `end_pos`). 

> Maybe I should see if I can do the same sorts of things I am doing with tokenize with the top-level parso parser?

Maybe that's better, but I doubt it will make a big difference (especially with the 3.10 changes coming). I feel like parso is pretty much in maintenance mode now - as well as Jedi. We are trying to keep it bug free and working. My focus is now on a Rust rewrite, which will most probably never find its way into Parso/Jedi, because the concepts are different (and the licensing will probably also be).

So feel free to do whatever with that information. :)

**Comment by davidhalter** [comment]
I guess I'm closing. If you really just want to have a default for the version, feel free to patch it and create a PR. It's probably less than 15min of work.

If there was another point that I missed, please let me know!
