### ISSUE TITLE
[usage]conditional stop?

### ISSUE THREAD

**Issue by shouldsee** [davidhalter/parso#210]
Dear authors, thanks for the great repo.

Just wondering, how would i stop my parsing to save computation?

Say I only wants the import section, and not anything afterwards. I cannot figure out
a easy way to pass argument into `parso.parse()` to subclass a parser. is there any callback 
mechanism?

```python
import os,sys
import parso

def main():
    print(123)
def blah():
    print(123)
#...
```

**Comment by davidhalter** [comment]
There's no such thing sorry. I also don't think this will ever exist here, so I'm going to close.

> Say I only wants the import section, and not anything afterwards.

I'm pretty sure there's no way to avoid parsing the whole thing, since imports can be at the end as well. If you just want a heuristic instead you can just use a heuristic with a bit of regex and just parse the parts you want.
