### ISSUE TITLE
YAML parsing

### ISSUE THREAD

**Issue by asmeurer** [davidhalter/parso#24]
@davidhalter mentioned to me on [Twitter](https://twitter.com/jedidjah_ch/status/932912266118336513) that parso could potentially be used to create a round-trippable YAML parser, if one has a tokenizer and a grammar. 

So I thought I'd open this issue to discuss the possibility. How hard is it to write a tokenizer? 

It looks like the grammar is context sensitive, which is expressed in the BNF grammar as production parameters (http://www.yaml.org/spec/1.2/spec.html, section 4.1).

Is this something that parso can handle? 

I'm also happy to have only a subset of YAML supported, so long as it's a commonly used one. My personal use-case is programmatically modifying .travis.yml files.

**Comment by davidhalter** [comment]
Just reading 4.1:

Indentation: Since YAML works like Python here, it's definitely possible to do that with the tokenizer.
Context: I don't really understand that all the way. But if it's just how newlines are handled, that should be possible.
Chomping: That's also possible with the tokenizer. Just one or two ifs.

There's also the question if you need to be able to handle all of that in the first version of such a parser.

For a tokenizer we could e.g. use the pygments YAML tokenizer and modify it to make it work with parso:
https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/data.py?at=default&fileviewer=file-view-default#data.py-33

Here's a haskell token list: https://hackage.haskell.org/package/YamlReference-0.10.0/docs/Text-Yaml-Reference.html

The grammar stuff is not so clear. It also depends how we handle indents and dedents. 

A scraped grammar (complete):
https://gist.github.com/tociyuki/3936873

A grammar (incomplete)
https://github.com/yaml/Yaml.NET/blob/master/doc/BNF%20Grammar.txt

Another grammar that probably makes most sense:
https://github.com/tzlaine/yaml/blob/master/doc/specs/yaml-LL1.txt

That's just my short research.

**Comment by davidhalter** [comment]
It's not on mine or anyone else's priority list. I'd still be happy to see this, if someone has the time.
