### ISSUE TITLE
cajarename

### ISSUE THREAD

**Issue by josifoski** [davidhalter/parso#39]
Yesterday I've installed ubuntu-mate 18.04.
Previosly jedi was installing without problems. I'm using it with geany (https://github.com/notetau/geany-jedi-complete)
sudo pip2 install parso
gives
...
Collecting parso
  Downloading https://files.pythonhosted.org/packages/cd/3e/5908f9577dbd1e5df53e64349bfd11e46b726c1e4d8cd676bbe8aa4de316/parso-0.2.1-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 654kB/s 
cajarename 17.3.28 requires caja, which is not installed.
cajarename 17.3.28 requires gir1.2-gtk-3.0, which is not installed.
cajarename 17.3.28 requires python-caja, which is not installed.
cajarename 17.3.28 requires python-gi, which is not installed.
Installing collected packages: parso
Successfully installed parso-0.2.1

all those packages are installed via apt, and cajarename is in apt caja-rename
alias cajarename='caja-rename' is not helping
Any suggestion?

**Comment by davidhalter** [comment]
I have no idea. I makes no sense however that this is a parso issue, because parso doesn't have dependencies. I think this probably happens with everything that you're installing. Not sure if it is a problem, because parso installes fine (as the logs show).

Isn't Python 3 the default for 18.04? You probably have an installation of cajarename in Python 3.

I'm closing this, because this is not a parso issue, but I'm happy to keep this conversation going if you have more questions.
