### ISSUE TITLE
diff.py logs to root logger

### ISSUE THREAD

**Issue by density** [davidhalter/parso#9]
in various places in https://github.com/davidhalter/parso/blob/master/parso/python/diff.py, logging is done using the root logger instead of creating a separate logger using `logging.getLogger`. this makes it difficult to customize the logging behavior of parso separately from other loggers in one's app.

example:

https://github.com/davidhalter/parso/blob/0ec02e1d7feb8e79a238f79a06aa1749f02794c4/parso/python/diff.py#L119

**Comment by davidhalter** [comment]
You're absolutely right. A friend of mine was also telling me this. I need to fix it.

**Comment by davidhalter** [comment]
cc @feuermurmel

**Comment by dimaqq** [comment]
Guys, you do know that it's possible to branch logging based on module, right?

**Comment by davidhalter** [comment]
@dimaqq Yeah I know that I kind of forgot when I wrote it. Is the fix above wrong?

**Comment by dimaqq** [comment]
Not wrong, rather, perhaps unnecessary.

I for one am against proliferation of `logger = logging.getLogger()` 
I believe that logging infrastructure should handle logging policy based on source module of log events.

**Comment by davidhalter** [comment]
So what would you have done instead? Would you just have used `logging.debug` directly like I did? Maybe I just didn't get what you meant with `branch logging based on module` after all. :)

**Comment by dimaqq** [comment]
Yes, I advocate plain `logging.debug`.

Sorry I was too terse, I meant that logging infrastructure can decide what to do with emitted log record based on the module name attached to each record.

Admittedly there are 2 schools of thought here, let's call them Django style (https://docs.djangoproject.com/en/1.11/topics/logging/) and plain style (https://docs.python.org/3/library/logging.html#module-level-functions).
So much for "only one obvious way."
If most of your library users (projects) lean a certain fay, that may be a good indication for `parso` too...

**Comment by davidhalter** [comment]
Well if you branch based on source module you would need to work with `sys._getframe` or something similar and my experience is that that is extremely slow. That's just the reason why I wouldn't do it. Using `sys._getframe` would be nice for logging, but it can really really slow down a program by a factor of like 10 (has happened to me before).

**Comment by dimaqq** [comment]
`logRecord` (if created) already contains caller's `module` and `pathname`, that is caller frame is already computed for you : https://docs.python.org/2/library/logging.html#logrecord-attributes
Record is created if `logging.root.level` is appropriate (if it might be logged, actual output is up to handlers).
Simply put, `logging.debug()` creates a record if `logging.basicConfig(level=logging.DEBUG)` or lower was called.
That's plain-style logging.

In the Django-style logging, each module has own logger and that logger has a level set, implicitly or via config. I believe that's done in the name of performance, at the cost of flexibility: configuration is needed in advance, but then e.g. only one sub-sub-module had debug set while the rest of the program doesn't produce records at all.

A Django-based server may provide admin endpoint to change loggers' levels at runtime. So when something's failing, a dev could bump up log levels, run some requests and maybe glean data from live system as to why.

The other way to build large systems is to log a lot, stream all those logs to some aggregation service (in-house ELK or LaaS like splunk, sumo, bigtable), and when system is (or was) failing, a dev searches for logs in the that service dashboard. Because it's designed to support after-the-fact use case, filtering cannot be up-front. Instead, usually there's a different retention policy (e.g. errors are kept for a year, debug for a week).

So, in a sense, we are back to plain-style logging being the norm. I think we are :)

**Comment by davidhalter** [comment]
I see.

Well it's just that with the approach that you're proposing people don't really have the choice. So having your own ELK is too much work for many small companies. They'd rather just log what they want to the sys log and inspect that.

**Comment by dimaqq** [comment]
Sure thing.

Not `syslog` though, as message size limit makes it impractical for tracebacks.

Best is stdout or stderr, if service is ran under a supervisord, or in a container. That way logging infrastructure is separate from the application.

Sadly logging to a file is still the norm for small native deployments. (https://www.youtube.com/watch?v=98EgoBLp-QM)

**Comment by cthrax** [comment]
Was this released? I'm on 0.1.0 from pypi and I'm still getting the root level logging.

**Comment by davidhalter** [comment]
It's not released yet. Release is coming soon. It will be released in 0.1.1.
