### ISSUE TITLE
Make `Scope._search_in_scope` public and documented

### ISSUE THREAD

**Issue by jack1142** [davidhalter/parso#99]
In my opinion, this could be a very useful utility and I think it would be nice if we weren't only limited to `iter_*` methods that are provided and make our own generators to properly go through whole scope.

**Comment by davidhalter** [comment]
It is intentionally not public. Those functions are so small, if you want to use them, just copy them and have them in a local module as helpers. I have done the same thing with ambiguous function definitions in `jedi`'s `parser_utils.py`. IMO it's not a good idea to have functions lingering around without a clear purpose.

I'm closing, because I'm not in favor of publishing it, since `_search_in_scope` doesn't have a real spec.
